version: "2"

services:
  
  mongo:
    image: mongo:4-xenial
    ports:
      - 27017:27017
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes: 
      - mongo-data:/etc/mongo
      
volumes: 
  mongo-data: