version: "3.7"

services: 

  shopping-list:
    image: shopping-list-mongo-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - backend
  
  mongo:
    image: mongo:4-xenial
    networks: 
      - backend
    volumes: 
      - mongo-data:/etc/mongo
      
volumes: 
  mongo-data:

networks: 
  backend:
    