version: "2"

services: 

  shopping-list:
    image: shopping-list-mongo-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
  
  mongo:
    image: mongo:4-xenial
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes: 
      - mongo-data:/etc/mongo
      
volumes: 
  mongo-data: