version: "2"

services:
  
  mongo:
    image: mongo:4-xenial
    ports:
      - 27018:27017
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ShoppingList
    volumes: 
      - mongo-data:/etc/mongo
      
volumes: 
  mongo-data: