version: "3.7"

services: 

  shopping-list:
    image: boyankov/shopping-list:mongo-4-xenial
    ports:
      - 80:8080
    networks:
      - backend
  
  mongo:
    image: boyankov/mongo:4-xenial-shopping-list-app
    networks: 
      - backend
    volumes: 
      - mongo-data:/etc/mongo
    deploy:
      placement:
        constraints: [node.hostname == node1]
      
volumes: 
  mongo-data:

networks: 
  backend:
    
# Note:
# Use this file to deploy on swarm
