# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

def obtain_pods

  # Pods
  pod "SimpleLogger", :git => "https://github.com/thinkaboutiter/SimpleLogger.git", :tag => "1.2.1"
  pod 'SnapKit', '~> 4.0'
  pod 'Starscream', '~> 3.0'

end

target 'BubblyChatClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BubblyChatClient
  obtain_pods

end
